set(_CATKIN_CURRENT_PACKAGE "simulator_plugins")
set(simulator_plugins_VERSION "0.0.0")
set(simulator_plugins_MAINTAINER "pranjal <pranjal@todo.todo>")
set(simulator_plugins_PACKAGE_FORMAT "2")
set(simulator_plugins_BUILD_DEPENDS "mav_msgs" "nav_msgs" "roscpp" "rospy")
set(simulator_plugins_BUILD_EXPORT_DEPENDS "mav_msgs" "nav_msgs" "roscpp" "rospy")
set(simulator_plugins_BUILDTOOL_DEPENDS "catkin")
set(simulator_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(simulator_plugins_EXEC_DEPENDS "mav_msgs" "nav_msgs" "roscpp" "rospy")
set(simulator_plugins_RUN_DEPENDS "mav_msgs" "nav_msgs" "roscpp" "rospy")
set(simulator_plugins_TEST_DEPENDS )
set(simulator_plugins_DOC_DEPENDS )
set(simulator_plugins_URL_WEBSITE "")
set(simulator_plugins_URL_BUGTRACKER "")
set(simulator_plugins_URL_REPOSITORY "")
set(simulator_plugins_DEPRECATED "")